# TCL File Generated by Component Editor 20.1
# Tue Oct 07 17:30:03 AEDT 2025
# DO NOT MODIFY


# 
# vga_streaming "vga_streaming" v1.0
#  2025.10.07.17:30:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_streaming
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_streaming
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_streaming
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_streaming
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_streaming.sv SYSTEM_VERILOG PATH vga_streaming.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_streaming
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_streaming.sv SYSTEM_VERILOG PATH vga_streaming.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 640
set_parameter_property WIDTH DEFAULT_VALUE 640
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter HEIGHT INTEGER 480
set_parameter_property HEIGHT DEFAULT_VALUE 480
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT TYPE INTEGER
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HEIGHT HDL_PARAMETER true
add_parameter PIXEL_BITS INTEGER 12
set_parameter_property PIXEL_BITS DEFAULT_VALUE 12
set_parameter_property PIXEL_BITS DISPLAY_NAME PIXEL_BITS
set_parameter_property PIXEL_BITS TYPE INTEGER
set_parameter_property PIXEL_BITS UNITS None
set_parameter_property PIXEL_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIXEL_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point vga_streaming
# 
add_interface vga_streaming avalon_streaming start
set_interface_property vga_streaming associatedClock clock
set_interface_property vga_streaming associatedReset reset
set_interface_property vga_streaming dataBitsPerSymbol 10
set_interface_property vga_streaming errorDescriptor ""
set_interface_property vga_streaming firstSymbolInHighOrderBits true
set_interface_property vga_streaming maxChannel 0
set_interface_property vga_streaming readyLatency 0
set_interface_property vga_streaming ENABLED true
set_interface_property vga_streaming EXPORT_OF ""
set_interface_property vga_streaming PORT_NAME_MAP ""
set_interface_property vga_streaming CMSIS_SVD_VARIABLES ""
set_interface_property vga_streaming SVD_ADDRESS_GROUP ""

add_interface_port vga_streaming data data Output 30
add_interface_port vga_streaming endofpacket endofpacket Output 1
add_interface_port vga_streaming ready ready Input 1
add_interface_port vga_streaming startofpacket startofpacket Output 1
add_interface_port vga_streaming valid valid Output 1


# 
# connection point BPM_estimate
# 
add_interface BPM_estimate conduit end
set_interface_property BPM_estimate associatedClock clock
set_interface_property BPM_estimate associatedReset ""
set_interface_property BPM_estimate ENABLED true
set_interface_property BPM_estimate EXPORT_OF ""
set_interface_property BPM_estimate PORT_NAME_MAP ""
set_interface_property BPM_estimate CMSIS_SVD_VARIABLES ""
set_interface_property BPM_estimate SVD_ADDRESS_GROUP ""

add_interface_port BPM_estimate BPM_estimate bpm_estimate Input 9


# 
# connection point beat_pulse
# 
add_interface beat_pulse conduit end
set_interface_property beat_pulse associatedClock clock
set_interface_property beat_pulse associatedReset ""
set_interface_property beat_pulse ENABLED true
set_interface_property beat_pulse EXPORT_OF ""
set_interface_property beat_pulse PORT_NAME_MAP ""
set_interface_property beat_pulse CMSIS_SVD_VARIABLES ""
set_interface_property beat_pulse SVD_ADDRESS_GROUP ""

add_interface_port beat_pulse beat_pulse beat_pulse Input 2

