// vga_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 711

`timescale 1 ps / 1 ps
module vga_mm_interconnect_0 (
		input  wire        video_pll_0_vga_clk_clk,                                //                              video_pll_0_vga_clk.clk
		input  wire        sdram_pixel_getter_0_reset_reset_bridge_in_reset_reset, // sdram_pixel_getter_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] sdram_pixel_getter_0_avalon_master_0_address,           //             sdram_pixel_getter_0_avalon_master_0.address
		output wire        sdram_pixel_getter_0_avalon_master_0_waitrequest,       //                                                 .waitrequest
		input  wire        sdram_pixel_getter_0_avalon_master_0_read,              //                                                 .read
		output wire [15:0] sdram_pixel_getter_0_avalon_master_0_readdata,          //                                                 .readdata
		output wire        sdram_pixel_getter_0_avalon_master_0_readdatavalid,     //                                                 .readdatavalid
		output wire [15:0] mm_bridge_0_s0_address,                                 //                                   mm_bridge_0_s0.address
		output wire        mm_bridge_0_s0_write,                                   //                                                 .write
		output wire        mm_bridge_0_s0_read,                                    //                                                 .read
		input  wire [15:0] mm_bridge_0_s0_readdata,                                //                                                 .readdata
		output wire [15:0] mm_bridge_0_s0_writedata,                               //                                                 .writedata
		output wire [0:0]  mm_bridge_0_s0_burstcount,                              //                                                 .burstcount
		output wire [1:0]  mm_bridge_0_s0_byteenable,                              //                                                 .byteenable
		input  wire        mm_bridge_0_s0_readdatavalid,                           //                                                 .readdatavalid
		input  wire        mm_bridge_0_s0_waitrequest,                             //                                                 .waitrequest
		output wire        mm_bridge_0_s0_debugaccess                              //                                                 .debugaccess
	);

	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_waitrequest;   // mm_bridge_0_s0_translator:uav_waitrequest -> sdram_pixel_getter_0_avalon_master_0_translator:uav_waitrequest
	wire  [15:0] sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdata;      // mm_bridge_0_s0_translator:uav_readdata -> sdram_pixel_getter_0_avalon_master_0_translator:uav_readdata
	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_debugaccess;   // sdram_pixel_getter_0_avalon_master_0_translator:uav_debugaccess -> mm_bridge_0_s0_translator:uav_debugaccess
	wire  [32:0] sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_address;       // sdram_pixel_getter_0_avalon_master_0_translator:uav_address -> mm_bridge_0_s0_translator:uav_address
	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_read;          // sdram_pixel_getter_0_avalon_master_0_translator:uav_read -> mm_bridge_0_s0_translator:uav_read
	wire   [1:0] sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_byteenable;    // sdram_pixel_getter_0_avalon_master_0_translator:uav_byteenable -> mm_bridge_0_s0_translator:uav_byteenable
	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdatavalid; // mm_bridge_0_s0_translator:uav_readdatavalid -> sdram_pixel_getter_0_avalon_master_0_translator:uav_readdatavalid
	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_lock;          // sdram_pixel_getter_0_avalon_master_0_translator:uav_lock -> mm_bridge_0_s0_translator:uav_lock
	wire         sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_write;         // sdram_pixel_getter_0_avalon_master_0_translator:uav_write -> mm_bridge_0_s0_translator:uav_write
	wire  [15:0] sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_writedata;     // sdram_pixel_getter_0_avalon_master_0_translator:uav_writedata -> mm_bridge_0_s0_translator:uav_writedata
	wire   [1:0] sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_burstcount;    // sdram_pixel_getter_0_avalon_master_0_translator:uav_burstcount -> mm_bridge_0_s0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (33),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) sdram_pixel_getter_0_avalon_master_0_translator (
		.clk                    (video_pll_0_vga_clk_clk),                                                                 //                       clk.clk
		.reset                  (sdram_pixel_getter_0_reset_reset_bridge_in_reset_reset),                                  //                     reset.reset
		.uav_address            (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (sdram_pixel_getter_0_avalon_master_0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (sdram_pixel_getter_0_avalon_master_0_waitrequest),                                        //                          .waitrequest
		.av_read                (sdram_pixel_getter_0_avalon_master_0_read),                                               //                          .read
		.av_readdata            (sdram_pixel_getter_0_avalon_master_0_readdata),                                           //                          .readdata
		.av_readdatavalid       (sdram_pixel_getter_0_avalon_master_0_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                                    //               (terminated)
		.av_byteenable          (2'b11),                                                                                   //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                    //               (terminated)
		.av_begintransfer       (1'b0),                                                                                    //               (terminated)
		.av_chipselect          (1'b0),                                                                                    //               (terminated)
		.av_write               (1'b0),                                                                                    //               (terminated)
		.av_writedata           (16'b0000000000000000),                                                                    //               (terminated)
		.av_lock                (1'b0),                                                                                    //               (terminated)
		.av_debugaccess         (1'b0),                                                                                    //               (terminated)
		.uav_clken              (),                                                                                        //               (terminated)
		.av_clken               (1'b1),                                                                                    //               (terminated)
		.uav_response           (2'b00),                                                                                   //               (terminated)
		.av_response            (),                                                                                        //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                    //               (terminated)
		.av_writeresponsevalid  ()                                                                                         //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (16),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (33),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) mm_bridge_0_s0_translator (
		.clk                    (video_pll_0_vga_clk_clk),                                                                 //                      clk.clk
		.reset                  (sdram_pixel_getter_0_reset_reset_bridge_in_reset_reset),                                  //                    reset.reset
		.uav_address            (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (sdram_pixel_getter_0_avalon_master_0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (mm_bridge_0_s0_address),                                                                  //      avalon_anti_slave_0.address
		.av_write               (mm_bridge_0_s0_write),                                                                    //                         .write
		.av_read                (mm_bridge_0_s0_read),                                                                     //                         .read
		.av_readdata            (mm_bridge_0_s0_readdata),                                                                 //                         .readdata
		.av_writedata           (mm_bridge_0_s0_writedata),                                                                //                         .writedata
		.av_burstcount          (mm_bridge_0_s0_burstcount),                                                               //                         .burstcount
		.av_byteenable          (mm_bridge_0_s0_byteenable),                                                               //                         .byteenable
		.av_readdatavalid       (mm_bridge_0_s0_readdatavalid),                                                            //                         .readdatavalid
		.av_waitrequest         (mm_bridge_0_s0_waitrequest),                                                              //                         .waitrequest
		.av_debugaccess         (mm_bridge_0_s0_debugaccess),                                                              //                         .debugaccess
		.av_begintransfer       (),                                                                                        //              (terminated)
		.av_beginbursttransfer  (),                                                                                        //              (terminated)
		.av_writebyteenable     (),                                                                                        //              (terminated)
		.av_lock                (),                                                                                        //              (terminated)
		.av_chipselect          (),                                                                                        //              (terminated)
		.av_clken               (),                                                                                        //              (terminated)
		.uav_clken              (1'b0),                                                                                    //              (terminated)
		.av_outputenable        (),                                                                                        //              (terminated)
		.uav_response           (),                                                                                        //              (terminated)
		.av_response            (2'b00),                                                                                   //              (terminated)
		.uav_writeresponsevalid (),                                                                                        //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                     //              (terminated)
	);

endmodule
